### ISSUE TITLE
Render messages

### ISSUE THREAD

**Issue by plexus** [clojureverse/clojurians-log-app#1]
Currently message text is displayed as is, whereas it really is a kind of markup format that should be parsed and rendered. Most people think of it as Markdown, but it's definitely not real markdown, but rather a subset of markdown, plus various slack-specific things added on top.

So using a full-blown markdown parser for this would be overkill (and render certain things incorrectly).

I would start with simple regex replacements, this should get us quite far. The problem there is that inside e.g. a source code block other syntax should be ignored, so a proper approach would involve first "parsing" the text into blocks (paragraphs, source code, block quotes, lists), then processing each of these with regexes.

For a (incomplete) article about what slack supports, see [Format your messages](https://get.slack.help/hc/en-us/articles/202288908-how-can-i-add-formatting-to-my-messages-)

Things to support (roughly in order of importance, we can do these one at a time)

- [x] username links (e.g. `<@U7DT92B9R>`)
- [x] source code blocks (delimited with triple backticks)
- [ ] regular links (delimited with greater than/lower than, e.g. `<http://foo.bar>`)
- [ ] emoji (e.g. `:slightly_smiling_face:`)
- [x] inline markup (bold, italic, monospace, strikethrough)
- [ ] channel links `<#C03S1KBA2>` (pre 2016-08) or `<#C03S1KBA2|clojure>` (post 2016-08)

**Comment by camachom** [comment]
Hello!
I'm new to Clojure and would love to give at least one of the tasks on this issue a try. The explanation is pretty clear, so I think I have everything to start.

**Comment by plexus** [comment]
Hi Martin,

That's awesome! Welcome to the team :)

See if the instructions for starting the app and loading the demo data work
for you. So far I've only tried them myself so it would be good to verify
that they actually work for others.

Ping me any time if you have questions. You can also make a pull request
early on with whatever code you already have, that makes it easy to talk
about the approach you're taking and maybe provide some feedback.

Good luck!

**Comment by camachom** [comment]
Hi Arne,
The instructions worked perfectly. Finally got some time to work on this issue today. I'm sure you will have a lot of feedback on my PR/approach. Excited to see what you think!

**Comment by jxa** [comment]
Ah I just noticed this issue. Sorry if I have stepped on your toes @camachom it wasn't what I intended. I downloaded the application before a long plane trip and started hacking on the parser #11 before I saw that you were also working on it.
 
That's what I get for being too cheap to pay for wifi on a plane :D

**Comment by camachom** [comment]
@jxa no worries! Let's just see how @plexus wants to move forward. I'm just moving a little slow because I'm learning as I go. 

Also, I noticed that channels need to be properly rendered as well. They show up as ` <#C0744GXCJ|cursive>` right now. Could be another task to add.

**Comment by plexus** [comment]
Looking at both of your PR's it seems they don't actually conflict, but the parsing that @jxa has done needs to be hooked up with the username querying that @camachom has done. I'm going to merge both, then we can continue from there.

The next step would be to convert the output of Instaparse to Hiccup (that should be relatively straightforward with `clojure.walk/postwalk`), replacing username references on the way.

After that we can do the same for Channels.

It seems some time in August 2016 Slack started adding the channel name to the log, e.g. `<#C03S1KBA2|clojure>`. Before that the channels just show up as `<#C03S1KBA2>`. So we still need to query for channel names, but only if the name isn't already there yet. If all the names are present, then we should avoid doing any queries.

@jxa and @camachom please put a message here when you start working on something so we don't duplicate the effort.

**Comment by camachom** [comment]
@jxa Coordinating on such a small task is probably not worth the time. I won't be able to work on this until Saturday. I'll checkin then to see if there is anything left to be done. Does that sound good?

**Comment by plexus** [comment]
@camachom I was thinking if you both want to have something to contribute then @jxa could leave the channel handling up to you.

Also there will be plenty of other things after this is done :)

**Comment by camachom** [comment]
That sounds good! I'll work on the channel handling then.

**Comment by jxa** [comment]
cool. I'll have some more time this weekend to take this a bit further. @camachom if you get stuck or want to chat real time you can message me. I'm xandrews on clojurians slack

**Comment by camachom** [comment]
From working on the channels today, I see that instaparse can output hiccup. I assume the intent is to change the the placeholder keys (":slack-id :inline-code, etc") with actual html tags. If that's the case, my though is to still use simple regexs to find/replace the users/channels before passing the message to the parser. What do you think @jxa ? 

Initially, I wanted to do everything within instaparse since we are already using it, but I could not find a clear way to do the above.

**Comment by jxa** [comment]
@camachom My thought was to replace the slack-ids with user names after instaparse has parsed them out. I'm thinking a simple pipeline like this:

```clojure
(-> message-text
    (parse)
    (lookup-users)
    (lookup-channels) ;; if necessary
    (render-hiccup))
```

where the `lookup-usernames` would take our parse output vector and return a new vector with all user ids replaced by the user info we look up from our database. For example:

```clojure
(lookup-users [[:undecorated "Hi "] [:user-id "U1234567890"]])
;; => [[:undecorated "Hi "] [:user {:user-id "U1234567890" :user-name "xandrews"}]]
```

I'm not saying it needs to be a map with more than just the username in there. But I could imagine the render someday wanting more info about the user, like avatar url or something (for a hover effect, for example). The map would give us the flexibility to add more stuff in the future.

**Comment by jxa** [comment]
@camachom I think the issue you encounter with your regex may be overly greedy matching. A repetition such as `#"\S+"` (one or more consecutive non-whitespaces) would match the terminal `>` in the channel. The way you can handle it is to use something like what I did for inline-code
```
inline-code = <"`"> #"[^`]+" <"`">
```
It is handled in three parts. First we match the backtick. Then we match anything up until the next backtick, but not including it. Finally the backtick is matched.

I suspect you could use a similar approach for name:
```
name = <"|"> #"[^>]+"
```

**Comment by jxa** [comment]
@camachom good catch on the emoji. I'll fix that

**Comment by Odie** [comment]
Hi all!

Just want to direct your attention to #34. It's a little parser using only regex to try parsing slack messages. It is meant to address performance issues uncovered during route testing. I hope I'm not stepping on anybody's toes here. 

The new parser is still pretty rough. I'd love to hear your feedback. Please let me know if there are obvious inputs that might cause the parser to fail!

**Comment by plexus** [comment]
Closing this as we've been parsing messages just fine. There are still some pages where the parser errors out. It would be great if we could catch those errors, log them, and render the raw message instead.
