### ISSUE TITLE
Allow starting the server on a different host

### ISSUE THREAD

**Issue by oxalorg** [clojureverse/clojurians-log-app#100]
I'm using WSL so starting the server on `localhost` in wsl does not make it availbale on windows. It needs to be served via `0.0.0.0`

Having an optional configuration `:http :host` which defaults to localhost should solve this issue.

If this sounds good and is needed, I can send a PR for it.

**Comment by plexus** [comment]
Yes, sounds good.

**Comment by oxalorg** [comment]
Fixed in #103
