### ISSUE TITLE
Show display name instead of handle

### ISSUE THREAD

**Issue by plexus** [clojureverse/clojurians-log-app#104]
We display people's "handle" (login name), instead of the display name they have configured.

Show the display name instead.

**Comment by oxalorg** [comment]
This is a sample data with relavent attributes from the users.edn:

```
{:user-profile/display-name-normalized "plexus"
 :user/name "plexus"
 :user-profile/real-name-normalized "Arne Brasseur"
 :user-profile/display-name "plexus"
 :user/real-name " Arne Brasseur ", 
 :user/slack-id "U07FP7QJ0",
 :user-profile/real-name "Arne Brasseur",
 ...
}
```

We'll have to check if there is any difference between `:user/real-name` and `:user-profile/real-name`.

**Comment by plexus** [comment]
And `:user-profile/real-name-normalized`. I'm not sure how much difference these make, maybe see if you can find some users for which these values are not the same, so we can see what the difference is.

**Comment by plexus** [comment]
here are the slack docs: https://api.slack.com/types/user

**Comment by oxalorg** [comment]
Yes they're most likely the same, but I'll still confirm it by testing it with some data we have.
