### ISSUE TITLE
Show stats of volume per date range

### ISSUE THREAD

**Issue by plexus** [clojureverse/clojurians-log-app#105]
Given a date range (e.g. 2020-09-20 - 2020-10-05), find out how many messages were posted, and how many unique users posted messages.

I think we can do this in stages

- add query functions so we can do this from a REPL
- expose a route that takes the dates as query params and shows the numbers -> this can be super bare bones, only accessible via url hacking
- a nice version, have widgets to pick the dates, show a line graph of volume, split out per channel, etc.

For IT Revolution I think the first one (repl helper) is good enough, I would also do the second one (basic route so you can access it without having to ssh to the machine). The third one is where most of the work is, and we'll punt on that for now.

**Comment by oxalorg** [comment]
Fixed in #120
