### ISSUE TITLE
Fix link when clicking on username

### ISSUE THREAD

**Issue by plexus** [clojureverse/clojurians-log-app#112]
The usernames link to `/team/<user-id>`, which 404s. I think those links used to go to `https://clojurians.slack.com/team/<user-id>`, but that we broke that at some point.

However instead of linking back to slack I think it would be better to just display user/profile information on our end. Slack uses an overlay panel for this. Having a standalone route would be fine though, we can maybe sprinkle in some javascript later to make it into an overlay.

**Comment by oxalorg** [comment]
This is a high level overview of what we need to accomplish:

1. We define a new route in routes.clj and it to def routes
2. Inside the route use the url path params (from context) to get slackid of the user
3. Create a new query and pass it the slack id and the context
4. Render the html view with the context

**Comment by oxalorg** [comment]
As per our call's discussion, @ArielA147 we've divided this task into two phases.

1. Create a route and return a simple "Hello {username}" html
2. Figure out the db/queries to make the final page

For the first phase we need to do the following steps:

Steps we need to take to get :
1. Create a new route mapping in `routes/routes`
2. Create a new route function which takes a request (you can probably name it something like `user-profile-route`
3. Create a context in that function
4. Add a `:data/username` attribute and fill it with request parameter (from the URL)
5. Pass this context to a view and add a `:response/html` attribute with a hiccup data structure
6. Finally render the response

**Comment by oxalorg** [comment]
Code is being worked on this branch: https://github.com/clojureverse/clojurians-log-app/tree/fix-username-link
