### ISSUE TITLE
idea for question threads

### ISSUE THREAD

**Issue by yogthos** [clojureverse/clojurians-log-app#12]
It would be great to parse out conversation threads out of the log, and display them stackoverflow style. If the Slack community starts using a convention of conversation threads when answering questions, that could provide the best of both worlds. You could have real time chat on Slack, and then structured Q&A threads in the log.

**Comment by yogthos** [comment]
Thinking a bit more about this, it would be great to make these threads editable in the log app, so people could add titles, corrections, and additional answers. This could possibly be a separate app built on top of the log db. The idea would be to start conversations on Slack, but then turns those into a permanent knowledge base site.

**Comment by plexus** [comment]
Rendering threads is certainly something we should look at. I'm not even sure if threaded messages show up at all at the moment.

There's an ongoing discussion on ClojureVerse about making it easy to follow-up on Slack messages with longer form discussion.

https://clojureverse.org/t/slack-integration/1643

**Comment by Odie** [comment]
Looks like each message is considered as being in a thread if it has a :thread_ts field, which will be the :ts of its parent message. See https://api.slack.com/docs/message-threading.

It doesn't look like the log-app is currently importing the :thread_ts field, so a bit of work is needed, for sure. If that field is imported, we can definitely grab messages belonging to the same thread and display it.

Any suggestions on the url format? Maybe something like /:channel/:thread-ts to show a specific thread?

**Comment by plexus** [comment]
It looks a couple things need to happen

- [ ] Add `:message/thread-ts` to the schema
- [ ] Import it in `clojurians-log.db.import`
- [ ] When fetching the messages for a day, also include messages that are children of a message of this day (replies might be sent the next day, and we'd still want to render those on the current day)
- [ ] Lift messages that have a parent out of the normal list of messages, and instead make them a child message of their parent
- [ ] Render threads inline (message 1 + all children of message 1  / message 2 / message 3 + children of 3 / etc) with some styling (indenting) to make the nesting clear
- [ ] Optionally add some JS to collapse / expand these threads
- [ ] When linking to a parent or child message, detect that this is the case, and render custom opengraph

I would maybe make it look like this:

Parent:

```
@plexus in #chestnut, 2018-03-08 | Clojurians Log

Hey have y'all seen this cool thing?
 - @Odie: yeah looks sweet
 - @foo: uhu cool
 - (7 more replies)
```

Child:

```
@plexus in reply to @Odie, in #chestnut, 2018-03-08 | Clojurians log

This looks really great, I'm sure it'll be useful!
in reply to @Odie: Check out my new library http://....
```

Links would be the same as now, /channel/date/ts. If the message has a ts that's the same as its thread_ts we can detect automatically that it's a thread.

**Comment by Odie** [comment]
Okay... looks pretty straightforward. =)

**Comment by plexus** [comment]
Thread rendering is working great so I'm going to close this. One thing we don't handle correctly yet is messages that go to both the thread and the channel, currently we only render those on the thread.
