### ISSUE TITLE
No messages since 2023-11-29?

### ISSUE THREAD

**Issue by danielcompton** [clojureverse/clojurians-log-app#142]
I noticed that the most recent messages logged seem to be as of 2023-11-29.

<img width="432" alt="Screenshot of Safari (18-12-23, 11-28-30 AM)" src="https://github.com/clojureverse/clojurians-log-app/assets/811954/ada204a5-708a-4dcc-ac4a-91d2cb94d3c9">

**Comment by plexus** [comment]
Hi Daniel,

This happens occasionally, we're normally still capturing messages, but the ingestion gets stuck. Or it may be you're just seeing an old version cached by cloudflare, it's set to cache quite aggressively.

In any case we're back up to date.
