### ISSUE TITLE
More attractive front page

### ISSUE THREAD

**Issue by plexus** [clojureverse/clojurians-log-app#2]
Currently we just show a list of all channels, with little to no markup. This could look a lot nicer. There are also several cool things we could do here.

Basics

- "What is this" (link to clojurians.net, and to the app)
- link to the github repo
- contact information

More fancy stuff

- show some statistics, e.g. which were the most popular channels in the last 7/30/90 days
- provide search functionality (we had this on the old site through google, we could do the same, or try our own datomic-based searching)
- show "popular" posts (many incoming links, requires server-side page view counting)

**Comment by green-coder** [comment]
I suggest opening a feature-based branch called "front-page" where multiple programmers can contribute to the front-page, as this issue describe multiples (non exhaustive) improvements, and merge it regularly in the master branch.

I will be happy to implement the client-side search functionality, with a realtime feedback on the search string being typed by the user.

**Comment by green-coder** [comment]
Having a branch per feature helps avoiding having unrelated commits interleaved, it could be better for readability but delay conflict resolutions. I am not sure if the difference matter, I was proposing that because the front page improvements might have a lot of tweak commits.

**Comment by plexus** [comment]
Ok, I can see that. Let's wait and see if more people are interested to work on this, then we can decide if we need a more involved workflow then just individual pull requests to master.

**Comment by plexus** [comment]
Expanded the initial issue a bit, I think the front page really needs an "about" section, for instance.
