### ISSUE TITLE
Empty message page

### ISSUE THREAD

**Issue by plexus** [clojureverse/clojurians-log-app#24]
Not sure what's going on, but logging this here so I don't forget. Seeing this currently on master, e.g.

http://localhost:4983/onyx/2018-02-03.html

According to the sidebar there's one message on this channel/day, but the page is empty.

**Comment by Odie** [comment]
The 1 message shows up fine for me when running from master (70555154e393b30a3efb8a4dfe4cb0e2a7006a88).
