### ISSUE TITLE
Improve channel page

### ISSUE THREAD

**Issue by plexus** [clojureverse/clojurians-log-app#3]
Currently when looking at a channel, you see a list of all dates on which there are messages. This could be more attractive, e.g. a calendar based view.

For less active channels we could provide links per week, instead of per day.

**Comment by miguelbermudez** [comment]
Hello!
I was looking into this.
I've noticed from previous pr's, that view change are being done in `views.clj` and I was bit confused (still consider myself new to clojure) since there is a `cljs` folder in the project containing a reagent/reframe app. Is that being used or any plans for it?

**Comment by miguelbermudez** [comment]
Hello!
I was looking into this.
I've noticed from previous pr's, that view change are being done in views.clj and I was bit confused (still consider myself new to clojure) since there is a cljs folder in the project containing a reagent/reframe app. Is that being used or any plans for it?

**Comment by plexus** [comment]
No, that's not being used, it was part of the project template but I think we're sticking to server side HTML for now.

**Comment by green-coder** [comment]
I suggest to remove the dead code as it waste each new comer's time and motivation. I ran into it today and was also confused while trying to understand what happens at the app's start.

**Comment by plexus** [comment]
Sure, sounds good to me!
