### ISSUE TITLE
Certain routes respond quite "slowly"

### ISSUE THREAD

**Issue by Odie** [clojureverse/clojurians-log-app#32]
While working on #31, I noticed that certain routes respond significantly slower than others.

On my machine, I'm getting the following:

| route | time |
|------|------|
| /                     | 5.28 ms |
| /healthcheck| 2.44 ms |
| /clojure          | 5.45 ms |
| /clojure/2018-02-02 | 582.56 ms |
| /clojure/2018-02-02/1517583973.000174 | 569.41 ms |

Though I haven't tried using criterium for a more accurate benchmark, we can still see that the last two routes is more than 100x slower. I'm not sure what kind of performance we're getting on the production server, but 500 ms seems "slow" especially given that there is no network latency. We're just measuring how long the ring handler took.

**Comment by Odie** [comment]
I profiled "/clojure/2018-02-02/1517583973.000174" using clj-async-profiler. Here are the items that are interesting.

clojurians-log.routes/log_route took up 95.2% of the request processing time.
clojurians-log.response/render => 88.5%
hiccup compiling/rendering => 74.3%
clojurians-log.slack_messages/message->hiccup => 69.5%
instaparse.core/parse => 68.5%

Given the table in the original post, instaparse might be taking somewhere around 400ms to parse the messages. One simple way to improve this is to just do a pmap over the messages with `message->hiccup` before sending the results for view generation.

---

Here's the resulting file for those who are interested.
[flamegraph-2018-03-16-13-15-18.svg.zip](https://github.com/clojureverse/clojurians-log-app/files/1817991/flamegraph-2018-03-16-13-15-18.svg.zip)

You can just open the svg with a web browser and see a somewhat interactive flamegraph.

**Comment by Odie** [comment]
Using pmap turns the timings into:

| route | time |
|------|------|
/clojure/2018-02-02 | 212.3 ms |
/clojure/2018-02-02/1517583973.000174 | 200.0 ms |

**Comment by plexus** [comment]
I already had some concerns that using instaparse would be quite slow. Using `pmap` is a great idea (perfect use case for it), but the  server we're using only has two cores so it might have less of an impact there.

There might be ways to rewrite the grammar so it does less backtracking. Even just reordering the rules could help, or perhaps a hand rolled parser would actually be in order.

In either case I'd like to see us start by adding many more test cases for the parser, and maybe include some benchmarking code as well. That will make it easy to experiment with different approaches.

**Comment by Odie** [comment]
After looking briefly at the grammar, it would appear that we’re not getting a whole lot of benefits by using instaparse.

We’re looking for 4 regex patterns that can appear anywhere in some free-form string. Since there is no actual grammar, running the messages through various regexes would work just as well. I think it’s  likely that this will be a lot faster. 

My previous experience with instaparse suggests that it tries all possible legal grammar paths and pick the one that seems successful. What this likely means for our usecase is that it is running the 4 regexes to extract *one token*. This effectively means we’re running many many many regexes to process one message.

Anyway, we should be able to get away with using 1 regex pass per unique pattern per message. Even with having to reshape the message to support the various rendering/conversion functions, it should be a net performance win.
