### ISSUE TITLE
NullPointerException in channel-day-offset

### ISSUE THREAD

**Issue by plexus** [clojureverse/clojurians-log-app#42]
Seems this is the main source of 500 errors at the moment

https://clojurians-log.clojureverse.org/cursive/2017-01-15.html
https://clojurians-log.clojureverse.org/datomic/2015-10-20.html
https://clojurians-log.clojureverse.org/figwheel/2017-03-06.html
https://clojurians-log.clojureverse.org/sql/2017-04-09.html

![2018-05-08-123719_1520x991_scrot](https://user-images.githubusercontent.com/32212/39752733-9cd2f9de-52bc-11e8-9b7d-3dc981bb01e0.png)

**Comment by Odie** [comment]
Looks like these are cases where there are no messages for that channel on the specified day.

Take the case of: https://clojurians-log.clojureverse.org/cursive/2017-01-15.html
The cursive channel has no log data on 2017-01-15. Things then fail when the log page header calculates tries to generate the prev/next day link.

I'm not sure what links people are following to reach these urls. We should probably respond with a 404 when no messages have been located for the specified channel & day.
