### ISSUE TITLE
Problem: we don't have a sitemap

### ISSUE THREAD

**Issue by danielcompton** [clojureverse/clojurians-log-app#50]
There are lots of pages in this site, but they are immutable after a day or two, and a few new ones are created each day. Creating a sitemap file would be useful for search engines to know where to crawl. I've noticed some recent pages haven't been indexed, improving indexing performance could be quite useful.

**Comment by plexus** [comment]
We've had a sitemap for some time now. Thanks @danielcompton for the suggestion and @kloimhardt for the implementation!
