### ISSUE TITLE
Prod is down

### ISSUE THREAD

**Issue by dustingetz** [clojureverse/clojurians-log-app#51]
https://clojurians-log.clojureverse.org/

Arne I know your plans for this were uncertain, so not sure if this is on purpose or not, but fyi.

**Comment by plexus** [comment]
Thanks for letting me know, it's not intentional. I'll have a look what's up.

**Comment by plexus** [comment]
I messed up... might take me a day or two to bring this back. Apologies!

**Comment by plexus** [comment]
The site is back up on a new server instance, still working on restoring the logs.
