### ISSUE TITLE
Problem: pages don't have a canonical rel

### ISSUE THREAD

**Issue by plexus** [clojureverse/clojurians-log-app#58]
We have urls for each individual message, so it's possible to link to them, but each of these contain the same content as the page for that channel/day, just with the message highlighted. This means a lot of duplicate content, which search engines don't like.

Solution: add a `<link rel="canonical" href=".../" />` to the page `<head>`

**Comment by plexus** [comment]
This has actually been flagged by google

> Duplicate without user-selected canonical

**Comment by dawran6** [comment]
Hi @plexus , I made the PR #65 to address this issue. This adds canonical urls like `<link href="/aleph/2018-02-08/1518108757.000638" rel="canonical">` into the head tag. Would you take a look when you get the chance? Thank you very much.

**Comment by plexus** [comment]
Thanks!
