### ISSUE TITLE
Problem: time controls are backwards

### ISSUE THREAD

**Issue by plexus** [clojureverse/clojurians-log-app#64]
This is a tiny thing but it bothers me to no end. A timeline goes left-to-right, so going left should be going into the past, but instead the back/forwards buttons go the other way around. We should swap these.

**Comment by dawran6** [comment]
I want to work on this. It seems some internal names are backward as well, for example, the style class names. I'll change those as well.

**Comment by plexus** [comment]
Thanks @dawran6, I've deployed and flushed the Cloudflare cache, looking much better now!
