### ISSUE TITLE
Problem: emoji aren't rendered

### ISSUE THREAD

**Issue by plexus** [clojureverse/clojurians-log-app#71]
Instead of `:slightly_smiling_face:` we should be showing :slightly_smiling_face:

**Comment by dawran6** [comment]
How can we solve this?

I think we need a giant map of emoji shortcodes, i.e. `:slightly_smiling_face:`, with their emoticons, i.e. :slightly_smiling_face:.

**Comment by plexus** [comment]
Yes, we'll have to figure out which unicode emoji corresponds with a given name. I feel like there has to be a csv or json floating around somewhere but I failed to quickly find something.

That would already be great. To take it further we could also render custom emoji (the parrorts, bmo, etc).

Bonus point for actually using the same image set as slack instead of relying on the OS fonts, assuming the license allows it.

This would all also be great preparation for eventually rendering emoji reactions.

**Comment by dawran6** [comment]
I created a library [dawran6/emoji](https://github.com/dawran6/emoji), which was inspired by this issue. If you are interested we can include it. Otherwise, we can just use the [emoji.edn](https://raw.githubusercontent.com/dawran6/emoji/master/resources/emoji.edn) file alone. Feel free to drop any comment about the library.

**Comment by plexus** [comment]
I'm not against adding a dependency, but in this case I don't think the added value justifies the extra indirection.

What I think would be more interesting is converting the edn file to json and making a repo with only that file. That way people can consume it from any language, and so we'll more likely get contributions. For instance when unicode adds a new block of emoji, or slack introduces new aliases.

**Comment by plexus** [comment]
This might be interesting: https://gist.github.com/oliveratgithub/0bf11a9aff0d6da7b46f1490f86a71eb
