### ISSUE TITLE
Question: How can I search the log?

### ISSUE THREAD

**Issue by teodorlu** [clojureverse/clojurians-log-app#81]
Hey!

Thanks for the great effort :+1: 

- Is there a canonical way to search the log?
- If not, is it possible to download all the HTML files to search manually?

Thanks!
Teodor

**Comment by plexus** [comment]
Use google with the `site:` directive, [here's an example](https://www.google.com/search?client=firefox-b-d&sxsrf=ACYBGNT3EhX1zeTqHD-rWTSGbS3ChT4-ng%3A1581949239825&ei=N6FKXqz9MZGasAfBkp3gAw&q=site%3Aclojurians-log.clojureverse.org+kaocha&oq=site%3Aclojurians-log.clojureverse.org+kaocha&gs_l=psy-ab.3...1602.2749..2908...0.0..0.179.1353.0j8......0....1..gws-wiz.deh67Tu9pZ4&ved=0ahUKEwjs9PeT5NjnAhURDewKHUFJBzwQ4dUDCAo&uact=5)

No, it is not possible to download all HTML files, neither do we supply the raw data. See [why don't you make the raw logs public?](https://github.com/clojureverse/clojurians-log-demo-data#why-dont-you-just-make-the-raw-logs-public)

**Comment by teodorlu** [comment]
OK, thanks for the reply and the reasoning around public availability.

I was asking because I was looking for a previous question I asked. A `site:` search didn't return anything, so I guess it hadn't been picked up by Google at that point.

Have an otherwise nice day!
