### ISSUE TITLE
Scrolling the page down does not show all the way down

### ISSUE THREAD

**Issue by green-coder** [clojureverse/clojurians-log-app#99]
A part of the page is displayed below the bottom of the viewport, even after scrolling all the way down.
Bug seen on Firefox, macosx, on the pages:
- https://clojurians-log.clojureverse.org/vrac/2020-08-23
- https://clojurians-log.clojureverse.org/vrac/2020-08-25

**Comment by plexus** [comment]
Thanks for the report. This should be fixed now. It was fixed in #97 already but I hadn't gotten around to deploying it yet.
